module.exports = {
  plugins: [require('@trivago/prettier-plugin-sort-imports')],
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  printWidth: 100,
  importOrder: [
    '^react(.*)$',
    '^next(.*)$',
    '^jotai(.*)$',
    '^@emotion/(.*)$',
    '^@pages/(.*)$',
    'chakra-ui(.*)$',
    'uuid',
    '^layouts/(.*)$',
    'ui',
    '^@ui/(.*)$',
    '^@templates/(.*)$',
    '^@atoms',
    '^@atoms/(.*)$',
    '^@models/(.*)$',
    '^@hooks/(.*)$',
    '^@common-hooks/(.*)$',
    '^@assets/(.*)$',
    '^@styles/(.*)$',
    '^@utils/(.*)$',
    '^~/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  endOfLine: 'lf',
};
