# Vercel cannot support organization repo deploy in hobby account.
# So I make workflow to push another repo to deploy to Vercel

name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  push_another_repository:
    if: github.repository == 'seeyouletter/seeyouletter-fe'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rm -rf .git

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install Dependencies
        run: pnpm install

      - name: Check build for deploy in stable 
        run: pnpm build

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: JengYoung
          destination-repository-name: seeyouletter-fe
          user-email: young_pallete@naver.com
          destination-directory: .

# name: HI
# on: 
#   push:
#     branches: ['main']

# jobs:
#   push-another-repo:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           repository: JengYoung/seeyouletter-fe
#           ref: main
#           token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      
#       - name: setup git config
#         run: |
#           git config user.name "JengYoung"
#           git config user.email "<young_pallete@naver.com>"
#           git remote set-url origin https://github.com/JengYoung/seeyouletter-fe.git

#       - run: git push -u origin main --force

# name: Push File

# on: push

# jobs:
#   copy-file:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Pushes test file
#       uses: dmnemec/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: 'test2.md'
#         destination_repo: 'dmnemec/release-test'
#         destination_folder: 'test-dir'
#         user_email: 'example@email.com'
#         user_name: 'dmnemec'
#         commit_message: 'A custom message for the commit'